### ISSUE TITLE
conflict resolution problem

### ISSUE THREAD

**Issue by tessus** [ThomasDaheim/ownNoteEditor#24] opened 2015-12-27 23:03 UTC
The following popup shows up, if the note on the filesystem changes:

<img width="370" alt="screen shot 2015-12-27 at 17 27 45" src="https://cloud.githubusercontent.com/assets/223439/12012476/cc15ab52-acc3-11e5-843f-46d0bd05d484.png">

This popup forces me to lose either the in-memory version or the local version. So no matter what, I lose data.

**Comment by ThomasDaheim** [comment] 2015-12-27 23:06
What could help here? A third option "Save local version as" to save local changes - other than that not much more what could be done in that case...

**Comment by tessus** [comment] 2015-12-27 23:21
It all depends on the point of view. In the current situation `Load` and `Discard current changes` is the same thing.
3 choices will be necessary to make sure that you won't lose any data, if you don't want to.

The most important thing is that the text above the buttons explains the situation so that everyone understands the consequences and what they imply.
(e.g. it doesn't matter whether you use the term `Load` or `Discard (current changes)` for one of the 3 choices as long as it is consistent and understandable.)

**Comment by ThomasDaheim** [comment] 2015-12-28 18:07
See commit for issues #25 - hope that resolves this one as well

**Comment by tessus** [comment] 2015-12-29 03:23
I think you might have forgotten to push your commit

**Comment by tessus** [comment] 2015-12-29 03:31
Yes, it creates a new dialog with 3 options, but when I click `Save` a new note named `New Note 3` is created. When I click `Save as new`, nothing happens.

**Comment by ThomasDaheim** [comment] 2015-12-29 09:30
Mmmh, let me have a look at that again.

**Comment by ThomasDaheim** [comment] 2015-12-29 10:33
Mixed up the buttons...

Now "Save as new" does what it says. When hitting "Save" nothing visual happens but the changed note in the file system is overwritten with the one in the editor. That seems to work here.

**Comment by tessus** [comment] 2015-12-29 19:33
Ok, the buttons are correct now, but I have a problem when trying to `Save as new`. This is the error:

<img width="353" alt="screen shot 2015-12-29 at 14 27 46" src="https://cloud.githubusercontent.com/assets/223439/12040654/f1b386d8-ae38-11e5-9783-bd36f64e82f5.png">

I don't understand how this can happen. You should get a dialog to enter the new name anyway, right?

**Comment by ThomasDaheim** [comment] 2015-12-29 19:41
The idea was that it should work as for "New Note" or "New Group": a new entry with a unique name is created and you can rename afterwards. Let me try this - I had added some logic to create a unique name that is not a timestamp or similar. Obviously, that didn't work out :-(

What note names & group names do you have? In my test cases it always worked...

**Comment by tessus** [comment] 2015-12-29 19:45
I have one group `TestGroup` and notes `Test`, `Test2` and `New Note 3`, which I can't delete for some reason.

**Comment by ThomasDaheim** [comment] 2016-01-01 16:28
Happy New Year!

Had a look at the issue and uploaded a fix for it.

**Comment by tessus** [comment] 2016-01-02 21:32
Happy New Year!

The naming of notes (when clicking `Save as new`) works now.
But for some reason I *sometimes* get 2 dialogs, when I change the note on the server and locally. First I get
<img width="357" alt="screen shot 2016-01-02 at 16 24 07" src="https://cloud.githubusercontent.com/assets/223439/12076184/0806dbdc-b16e-11e5-827c-c44ee7c48beb.png">

and then the correct one

<img width="446" alt="screen shot 2016-01-02 at 16 24 17" src="https://cloud.githubusercontent.com/assets/223439/12076186/13570c50-b16e-11e5-9fa0-934d6727cc05.png">

I haven't found the reason when and why this is happening, because it is not reproducible in a consistent manner.

**Comment by ThomasDaheim** [comment] 2016-01-03 18:11
I have managed to reproduce that once in 20+ attempts. But I also can't see the necessary sequence of actions to trigger this... I'll need to play around some more.

First dialogue comes when you're editing and then moving to another note. Second one comes when you're in editing and a changes happens behind your back. Not sure what needs to happen that both things are true at the same time.

**Comment by ThomasDaheim** [comment] 2018-03-04 16:25
Closing since not observed in the wild since then...

**Closed by ThomasDaheim** 2018-03-04 16:25 UTC
