### ISSUE TITLE
Resolution and Size

### ISSUE THREAD

**Issue by htrampe** [ThomasDaheim/ownNoteEditor#30] opened 2016-03-10 08:29 UTC
Hi! Great work so far. It would be really nice if the user can change the width of the overview-editor section. Reason is that the width of the note-section left is way to big :)

**Comment by htrampe** [comment] 2016-03-10 20:29
- Stored Value sounds perfect

- OK!
Keep it up - it's the best editor for the best opensource-cloud :+1:

**Comment by ThomasDaheim** [comment] 2016-03-13 14:30
That might take a bit longer...
I can now store preferences for width, height, percentage BUT the javafx control I'm using doesn't allow resizing of sections on the fly :-( Maybe I have to go with a command line parm fist, til I figure out how to do it with the mouse.

**Comment by htrampe** [comment] 2016-03-13 17:07
ok sounds crazy. But so long - it works great under linux and windows. Great work so pls keep it on :+1:

**Comment by ThomasDaheim** [comment] 2016-03-15 19:23
I have done some updates in branch "Issue-#30":

- store width & height of UI in preferences

- added parameter "leftColWidthInc", usage see README

Please have a look if thats what you're looking for - til I find out how it can be done on the UI...

**Comment by htrampe** [comment] 2016-03-15 20:27
Thx for fast develpoment. But i dont know what do u mean - where i need to change the parameter? In the GUI-Menue is no option for it and before iam searching i ask :+1:

**Comment by ThomasDaheim** [comment] 2016-03-16 08:04
Sorry, if that wasn't clear enough in the readme: its a new command line parameter:

```
To increase the width of the left panel (note names in classic, group names in oneNote)

--leftColWidthInc="-10" to "+20"

The number specifies the increase / decrease of percentage of the panel width of the full width. This can't yet be set using the UI.
```

**Comment by ThomasDaheim** [comment] 2016-03-16 08:04
Maybe I should rename it to "leftColWidthChg" since it can also be negative...

**Comment by htrampe** [comment] 2016-03-16 08:32
Hehe iam really sorry - i start the Editor under Ubuntu and the last line is:
`Building 75% > : run`

After that i can't use any commands. If i try to compile the project with the following line:
`./gradlew run --leftColWidthInc="+10"` 
i got an error...any tipps?

**Comment by ThomasDaheim** [comment] 2016-03-16 19:52
Linux and gradle - not my strong suits...

Not really a good idea here. Google indicates some options (https://stackoverflow.com/questions/23689054/problems-passing-system-properties-and-parameters-when-running-java-class-via-gr) but I have no quick answer here.

**Comment by htrampe** [comment] 2016-03-16 20:13
Hehe same problem for me under windows :+1: how u send the parameter to the software?

**Comment by ThomasDaheim** [comment] 2016-03-16 21:10
I have the following setup:

- ownNoteEditor.jar in directory
- all required jars in a lib subdirectory  (commons-cli-1.3.1.jar, commons-io-2.1.jar, jsoup-1.8.3.jar)

and run with 

java.exe -classpath .\OwnNoteEditor.jar;.\lib\* tf.ownnote.ui.main.OwnNoteEditorManager -lookAndFeel="oneNote" -leftColWidthInc="+0"

**Comment by htrampe** [comment] 2016-03-16 21:40
i give it a try thx!

**Comment by htrampe** [comment] 2016-03-16 21:58
Iam really sorry but i got different errors - iam not sure whats wrong...maybe i will wait until u realized the ui-changing. Pls dont feel stressed!

**Comment by ThomasDaheim** [comment] 2016-03-20 18:33
I have asked around for any idea: https://stackoverflow.com/questions/36068740/q-javafx8-resize-gridpane-columns-dynamically Lets see what would be the best way to do that.

**Comment by htrampe** [comment] 2016-03-21 12:19
Try it :+1: its not my area so i cant help :(

**Comment by ThomasDaheim** [comment] 2016-03-21 21:18
Have a look at the updated branch. I have tried to add something that enables mouse resizing. If it works OK, I would remove the command line parameter again...

**Comment by ThomasDaheim** [comment] 2016-03-21 21:23
Aaargh, don't try it - doesn't work as expected... Need to have some more thoughts on this, I fear

**Comment by htrampe** [comment] 2016-03-21 21:36
hehe ok i tryed it on ubuntu and win10 and it does not worked. I read the post to late. I cant say how happy iam that u worked on it so pls continue :+1: greatings!

**Comment by ThomasDaheim** [comment] 2016-03-21 22:24
Now you could give it a try and test it. I have only made a few checks so far...

I have limited the min & max size of the left panel since funny repainting happens once it gets too small or too big. But I'm sure I didn't test all possible combinations of things.

**Comment by htrampe** [comment] 2016-03-21 22:32
Under Linux it works fine. Max und Min is perfect. Re-Paiting - can't say cause i only have 5 groups but i will test it. Now it looks great and it is exactly what i mean so i give u a big big big thank you :+1: :+1: :+1: i keep testing :+1:

**Comment by htrampe** [comment] 2016-03-21 22:37
ok so i have re-painting when:

- sometimes delete a note and there is one note left in a group -> all groups will be re-paintet

- i've got very small windows when i drag a group or a note into a group

so far it works with these issue but that is still great :+1:

**Comment by ThomasDaheim** [comment] 2016-03-22 20:40
Will have a look at that over the quit Easter time... Let me know if you find anything else that needs fixing :smiley:

**Comment by htrampe** [comment] 2016-03-23 07:57
ok :+1: but it seems to be all - sometimes there are a few ghost-windwos when i drag and drop the groups but it could be my fault with java on linux...i will keep testing :+1:

**Comment by ThomasDaheim** [comment] 2016-03-25 17:01
I had a look at things under Win10:

- Delete a note leads to re-paint: as designed :-) otherwise I would need to do lots of details to update the tables
- Small windows when drag & drop: if its the name of the note / group on a grey background its also as designed
- ghost windows when drag & drop groups: can't seem to make that happen on my end

So I have done some final touches to the updates for issue #30 and would pull them into the master branch

**Comment by htrampe** [comment] 2016-03-25 17:16
Sounds great! I will test it under win10 and linux ubuntu 14.04. THX!

**Comment by ThomasDaheim** [comment] 2016-03-30 18:56
Closing this issue. if we run into further things we'll track them in new issues :-)

**Closed by ThomasDaheim** 2016-03-30 18:56 UTC
Labels: enhancement
